upstream backend{
    server app1:9009;
    server app2:9009;
    server app3:9009;
}
# here default would be round robin algorithm
server{
    listen 80;

    location / {
        proxy_pass http://backend;
    }
}